services:
  db:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5433"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo -d todo"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
    container_name: todo-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_DSN: postgres://auth_user:auth_password@db:5433/auth_db?sslmode=disable
      PORT: 8080
    ports: [ "8080:8080" ]